# ============================================
# VOICE COMMAND SHORTCUT SCRIPTS
# ============================================

morning_briefing:
  alias: Morning Briefing
  description: 'Comprehensive morning briefing with weather, calendar, and tasks'
  sequence:
  - action: tts.speak
    target:
      entity_id: media_player.piper_tts
    data:
      message: >
        Good morning, Fred.
        {% set now = now() %}
        Today is {{ now.strftime('%A, %B %d') }}.

        {% if states('weather.local_weather') != 'unknown' %}
        The weather today is {{ states('weather.local_weather') }}
        with a high of {{ state_attr('weather.local_weather', 'temperature') }} degrees.
        {% endif %}

        {% set events = state_attr('calendar.personal_tasks', 'events') | default([]) %}
        {% if events | length > 0 %}
        You have {{ events | length }} events on your calendar today.
        {% else %}
        You have no events scheduled for today.
        {% endif %}

        Have a great day!
  mode: single

goodnight:
  alias: Goodnight Routine
  description: 'Run complete goodnight routine'
  sequence:
  - action: light.turn_off
    target:
      entity_id: all
  - action: switch.turn_off
    target:
      entity_id:
        - switch.christmas_lights
        - switch.power_strip_outlet_1
        - switch.power_strip_outlet_2
  - action: tts.speak
    target:
      entity_id: media_player.piper_tts
    data:
      message: "Goodnight, Fred. All lights and devices are off. Sleep well."
  - delay:
      seconds: 5
  - action: switch.turn_off
    target:
      entity_id: light.fred_office_light
  mode: single

movie_time:
  alias: Movie Time
  description: 'Set the perfect movie-watching environment'
  sequence:
  - action: light.turn_on
    target:
      entity_id: light.fred_office_light
    data:
      brightness_pct: 20
      color_temp: 370
  - action: tts.speak
    target:
      entity_id: media_player.piper_tts
    data:
      message: "Movie mode activated. Lights dimmed. Enjoy your show!"
  mode: single

work_mode:
  alias: Work Mode
  description: 'Activate focused work environment'
  sequence:
  - action: light.turn_on
    target:
      entity_id: light.fred_office_light
    data:
      brightness_pct: 100
      color_temp: 250
  - action: switch.turn_on
    target:
      entity_id: switch.power_strip_outlet_1
  - action: tts.speak
    target:
      entity_id: media_player.piper_tts
    data:
      message: "Work mode activated. Office is ready. Let's be productive!"
  mode: single

im_home:
  alias: I'm Home
  description: 'Arrival routine for manual triggering'
  sequence:
  - condition: sun
    after: sunset
  - action: light.turn_on
    target:
      entity_id: light.fred_office_light
    data:
      brightness_pct: 80
  - action: switch.turn_on
    target:
      entity_id: switch.christmas_lights
  - action: tts.speak
    target:
      entity_id: media_player.piper_tts
    data:
      message: >
        Welcome home, Fred.
        {% if states('weather.local_weather') != 'unknown' %}
        It's currently {{ state_attr('weather.local_weather', 'temperature') }} degrees outside.
        {% endif %}
        How can I help you today?
  mode: single

im_leaving:
  alias: I'm Leaving
  description: 'Departure routine for manual triggering'
  sequence:
  - action: light.turn_off
    target:
      entity_id: all
  - action: switch.turn_off
    target:
      entity_id:
        - switch.christmas_lights
        - switch.power_strip_outlet_1
        - switch.power_strip_outlet_2
        - switch.power_strip_outlet_6
        - switch.power_strip_outlet_7
        - switch.power_strip_outlet_8
  - action: tts.speak
    target:
      entity_id: media_player.piper_tts
    data:
      message: "Goodbye, Fred. Lights and devices are off. Have a safe trip!"
  mode: single

power_strip_all_off:
  alias: Power Strip - All Off
  description: 'Turn off all power strip outlets'
  sequence:
  - action: switch.turn_off
    target:
      entity_id:
        - switch.power_strip_outlet_1
        - switch.power_strip_outlet_2
        - switch.power_strip_outlet_3
        - switch.power_strip_outlet_4
        - switch.power_strip_outlet_5
        - switch.power_strip_outlet_6
        - switch.power_strip_outlet_7
        - switch.power_strip_outlet_8
  - action: notify.persistent_notification
    data:
      message: "All power strip outlets turned off"
      title: "Power Strip"
  mode: single

power_strip_all_on:
  alias: Power Strip - All On
  description: 'Turn on all power strip outlets'
  sequence:
  - action: switch.turn_on
    target:
      entity_id:
        - switch.power_strip_outlet_1
        - switch.power_strip_outlet_2
        - switch.power_strip_outlet_3
        - switch.power_strip_outlet_4
        - switch.power_strip_outlet_5
        - switch.power_strip_outlet_6
        - switch.power_strip_outlet_7
        - switch.power_strip_outlet_8
  - action: notify.persistent_notification
    data:
      message: "All power strip outlets turned on"
      title: "Power Strip"
  mode: single

emergency_all_off:
  alias: Emergency - All Off
  description: 'Emergency shutdown of all devices'
  sequence:
  - action: switch.turn_off
    target:
      entity_id: all
  - action: light.turn_off
    target:
      entity_id: all
  - action: notify.persistent_notification
    data:
      message: "EMERGENCY: All devices and lights turned off"
      title: "Emergency Shutdown"
  mode: single
