# Christmas Lights Group
# This group controls all Christmas light devices together

- platform: group
  name: "All Christmas Lights"
  unique_id: all_christmas_lights
  entities:
    - switch.christmas_lights          # Sylvania Smart+ WiFi Plug (LocalTuya)
    - light.govee_curtain_lights       # Govee Curtain Lights (Official Govee LAN)
    - switch.tapo_outdoor_plug_1       # TP-Link Tapo Outdoor Plug 1
    # - light.govee_led_tree           # Govee LED Tree (to be added Monday)
